---
title: "DSC 520 Final Project Step 1"
author: "Milan Sherman"
date: "2/12/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Using data to increase a sports team's odds of winning has become standard in professional sports over the last 20 years.  In the early 2000s, the Oakland A's were early adopters, or even inventors of this approach to assembling a competitive baseball team as chronicled in the book (and movie) Moneyball (2011). While the strategy is not new, I am interested in identifying baseball metrics that are predictive of winning.  Given the amount of money that is generated by professional sports, the ability to gain a competitive edge via data is crucial.  In the current context, the ubiquity of leveraging data in sports has perhaps changes this approach from one of opportunity to a necessity in order to not lose ground on competitors.

## Research Questions

1. What batting metrics are most highly correlated with winning?  Some examples are batting average, on-base percentage, and slugging percentage  Which of these is most important?
2. Is situational hitting more important than the above metrics out of context?  That is, can a team with a lower batting average or number of hits consistently win games by batting better when runners are in scoring position?
4. What defensive metrics are most highly correlated with winning?
5. Should offensive or defensive metrics be weighted more heavily when having to make a decision between the two?  In which situations should one be favored over the other?
6. How important is pitching?  Or is pitching just the opposite of hitting?  That is, is predicting that the team with better pitching will win the same as predicting that the team with worse hitting will lose?


## Approach

My approach will be to identify significant predictors of winning using a logistic regression model, i.e., binary outcome of win or lose.  An exhaustive exploration of metrics that are predictive of winning is beyond the scope this project; indeed, what would really be needed is an exploration of new features that are predictive of winning in baseball, i.e., feature engineering.  Nonetheless, an approach which creates models via logistic regression in order to identify significant predictors is an important step in this direction.  

## Datasets


I currently have three datasets:

1.  Hitting - this is a comprehensive dataset for every at-bat in Major League baseball from 1901-2021.  It has over 4.2 million observations and 31 fields.  Each observation is by game by player, i.e., a player's hitting stats for a single game.  I got it from Kaggle last October when working on a personal project, but when I went back to Kaggle to reference the dataset it appears that it is no longer there. In addition to each at-bat, it also has the outcome of the game, which will allow me to relate batting statistics to winning and losing.  As this data is at the player level by game, I will need to create metrics like batting average and slugging percentage in order to create my model.  

2.  Game Logs - this is a comprehensive set of baseball game logs from 1871-2016.  It contains nearly 172k observation of 161 variables.  Each observation is a game, and just about every statistic that you could think of related to a baseball game is included. A full explanation of each of the fields is avaialble at [https://www.retrosheet.org/gamelogs/glfields.txt]. It was created by Dataquest 5 years from a compilation of 127 csv files.  Given the large number of variables in this dataset, I will  need to clean, reduce, and/or aggregate to variables of interest before creating a model with this data.  I got this dataset from data.world: [https://data.world/dataquest/mlb-game-logs]

3.  Moneyball - this is the same dataset that was used by the baseball manager and GM for the Oakland A's who the real life story of Moneyball is based on.  It was created 4 years ago by Wes Duckett, and is now public domain.  There are 1232 observations of 15 variables, where each observation is by team by season, i.e., team statistics for a season.   I think this may be the best dataset to start with as I know that the way it is aggregated is useful for answering my questions.  Working with this dataset will likely give me further ideas for how to use the other unaggregated datasets.  I got it from Kaggle: [https://www.kaggle.com/wduckett/moneyball-mlb-stats-19622012]

I also located a collection of datasets from Kaggle that have pitcher statistics, but have not yet determined if I will use that for this project.  


## Required Packages

Besides base R,  the Tidyverse package contains most of the libraries I will need, including dplyr, ggplot2, tidyr, readr, purrr, tibble, stringr, forcats, and others.  I will also need the stats package for logistic regression.

## Plots and Tables

It may be necessary to create aggregated metrics from the raw data, and it will certainly be necessary to examine the distribution of a variety of potential predictors.  I anticipate generating histograms and Q-Q plots to examine the distributions, as well as scatterplots to investigate how certain variables are related.  

## Questions and future steps

The next step is to identify common baseball metrics that may have predictive power, and to work with the Moneyball dataset to see which metrics are most promising for answering my questions, and to see which metrics might be useful but missing from that dataset.  My other two datasets are at a fine enough grain size that I could create those metrics based on my investigation of the Moneyball dataset.  